//-----------------------------------------------
//
//	This file is part of the Siv3D Engine.
//
//	Copyright (c) 2008-2023 Ryo Suzuki
//	Copyright (c) 2016-2023 OpenSiv3D Project
//
//	Licensed under the MIT License.
//
//-----------------------------------------------

# pragma once
# include "Common.hpp"

//
// このヘッダは、OpenAI の ChatGPT と DALL-E モデル、Embedding モデルを使用して、テキストベースの会話や画像生成、文章の埋め込みベクトルを取得のための API を提供します。主な関数は以下の通りです。
//
//	OpenAI::Chat::Complete() - ChatGPT にメッセージを送信し、返答メッセージを取得します。
//	OpenAI::Chat::CompleteAsync() - ChatGPTに メッセージを送信し、レスポンス（JSON）を取得する非同期タスクを返します。
//	OpenAI::Chat::GetContent() - ChatGPT のレスポンス（JSON）から、返答メッセージを抽出して返します。
//	OpenAI::Image::Create() - テキストに基づいて DALL-E モデルを使用して生成された画像を取得します。
//	OpenAI::Image::CreateAsync() - テキストに基づいて DALL-E モデルを使用して画像を生成する非同期タスクを返します。
//	OpenAI::Embedding::Create() - 文章の埋め込みベクトルを取得します。
//	OpenAI::Embedding::CreateAsync() - 文章の埋め込みベクトルを取得する非同期タスクを返します。
//	OpenAI::Embedding::GetVector() - Embedding モデルのレスポンス（JSON）から、埋め込みベクトルを抽出して返します。
//	OpenAI::Embedding::CosineSimilarity() - 2 つの埋め込みベクトルのコサイン類似度を計算して返します。
//
// This header provides an API to interact with OpenAI's ChatGPT, DALL-E, and Embedding models for text-based conversations, image generation, and obtaining embedding vectors for sentences. The main functions are as follows:
//
//	OpenAI::Chat::Complete() - Sends a message to ChatGPT and retrieves the response message.
//	OpenAI::Chat::CompleteAsync() - Returns an asynchronous task that sends a message to ChatGPT and retrieves the response (JSON).
//	OpenAI::Chat::GetContent() - Extracts and returns the response message from the ChatGPT response (JSON).
//	OpenAI::Image::Create() - Get one or more images generated by the DALL-E model based on the given text.
//	OpenAI::Image::CreateAsync() - Returns an asynchronous task that generates one or more images using the DALL-E model based on the given text.
//	OpenAI::Embedding::Create() - Retrieves the embedding vector for a given sentence.
//	OpenAI::Embedding::CreateAsync() - Returns an asynchronous task that retrieves the embedding vector for a given sentence.
//	OpenAI::Embedding::GetVector() - Extracts and returns the embedding vector from the Embedding model response (JSON).
//	OpenAI::Embedding::CosineSimilarity() - Calculates and returns the cosine similarity between two embedding vectors.
//

# include "OpenAI/Chat.hpp"
# include "OpenAI/Image.hpp"
# include "OpenAI/Embedding.hpp"
# include "OpenAI/Speech.hpp"
